### ISSUE TITLE
test not complete. no file to write code 

### ISSUE THREAD

**Issue by 8ceg6** [learn-co-curriculum/programming-univbasics-4-intro-to-hashes-lab#2]
there is test but there is no file to write code

**Comment by maxwellbenton** [comment]
Hi @8ceg6,

Thank you for opening this issue. Please note - the file to write and tests code is located in this lesson's main directory (not in a sub-folder). The file is called intro_to_ruby_hashes_lab.rb and includes some starter code.

I am going to close this issue as it looks that this lab does have the file you are looking for. If, however, you are still experiencing this problem or are unable to open that file, please reopen this issue.
