### ISSUE TITLE
Intro to Hashes Lab

### ISSUE THREAD

**Issue by seung0708** [learn-co-curriculum/programming-univbasics-4-intro-to-hashes-lab#3]
There is no file to write and test code. Please advise

**Comment by maxwellbenton** [comment]
Hi @seung0708,

Thank you for opening this issue. Please note - the file to write and tests code is located in this lesson's main directory (not in a sub-folder). The file is called `intro_to_ruby_hashes_lab.rb` and includes some starter code.

I am going to close this issue as it looks that this lab does have the file you are looking for. If, however, you are still experiencing this problem or are unable to open that file, please reopen this issue.
